print("Informe os dados abaixo:")
print("x" * 30)
altura = float(input("Qual a altura do objeto : "))
base = float(input("Qual a base do objeto : "))
Soma = (altura * base)
print("x" * 30)
print(f"A calculo da area total do objeto é de {Soma:.2f}")
