print("Informe os dados abaixo:")
print("x" * 30)
altura = float(input("Qual a altura do objeto : "))
base = float(input("Qual a base do objeto : "))
Soma1á = (altura * base)
print("x" * 30)
print(f"A cálculo da área total do objeto é de: {Soma1á:.2f}")
